version: '3'

services:
  mobiage-db:
    image: postgres:11.16-alpine
    container_name: filmecinema-db
    restart: always
    ports:
      - "9191:5432"
    environment:
      POSTGRES_USER: "filmecinema"
      POSTGRES_DB: "filmecinema"
      POSTGRES_PASSWORD: "123456"

